### ISSUE TITLE
Add docker dependency installation task

### ISSUE THREAD

**Issue by padawanmohamed** [ebarault/ansible-role-gitlab-runner-docker#3]
I got the following error:
`changed: false, msg: Error connecting: Error while fetching server API version: (Connection aborted., FileNotFoundError(2, No such file or directory))}`
I solved the error by installing docker with geerlingguy.docker role
https://galaxy.ansible.com/geerlingguy/docker

**Comment by ebarault** [comment]
Hi @padawanmohamed ,
I updated the doc to specify that the module expects docker to be installed on the target host. The module is meant to run gitlab runner as a docker container, not to install docker. Installing docker could lead to conflicts on the target host.
