### ISSUE TITLE
Role not idempotent or am I using it wrong?

### ISSUE THREAD

**Issue by jonisno** [ebarault/ansible-role-gitlab-runner-docker#4]
When I run a playbook using this role it keeps creating a runner every time. Am I using it wrong, or is that intentional?

Worth noting I am running it just like the readme suggests.

**Comment by ebarault** [comment]
Hi @jonisno,

You should use `gitlab_runner_unregister_all = true` to make sure you don't have ghosts runners visible in gitlab-ci. I updated the doc and set it as default too.

Anyhow, the role can't create extra runners on the docker host.

**Comment by jonisno** [comment]
Thanks for the help, closing this issue :)
